config/routes.rb
Rails.application.routes.draw do

  resources :categories, except: [:show] do
    collection do
      get 'manage'
      get 'accept'
      get 'contact'
    end
  end

  root "categories#index"

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products
  has_attached_file :image, :styles =>{:medium => "200x200>"}


  PRICE = /\A\d+(?:\.\d{0,2})?\z/i

  validates :name, :presence => true,
  :length => {:within => 3..100}

  validates :description, :presence => true,
  :length => {:within => 3..250}

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :confirm_logged_in, :except => [:index, :contact]
  before_action :privilege, :except => [:index, :contact]
  before_action :reset_session, :only => [:index, :contact]

  def index
    @categories = Category.visible
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category created and wait for accept.'
      redirect_to(:action => 'manage')
    else
      render("new")
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:notice]='Category updated successfully.'
      redirect_to(:action => 'manage')
    else
      render('edit')
    end
  end

  def contact
  end

  #def delete
  #  @category = Category.find(params[:id])
  # @category.destroy
  # flash[:notice] = "Category '#{category.name}' destroyed successfully."
  #end
  def destroy
    @category = Category.find(params[:id])
    @products = @category.products.sorted
    @category.destroy if @products.each do |product| product.update_attributes(:visible => false)
    end
    flash.now[:notice]= "Category  destroyed sucessfully. All products with this category is invisible now"
    @categories = Category.all
  end

  def manage
    @categories = Category.all
  end

  def accept
    @category = Category.find(params[:id])
    @category.update_attributes(:visible => true)
    if @category.visible.present?
      flash[:notice]='Category updated successfully.'
      redirect_to(:action => 'manage')
    end
  end

  private

  def category_params
    params.require(:category).permit(:name,:description,:image, :visible)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(object)
    render(:partial => 'application/error_messages', :locals => {:object => object})
  end

  def logged_in?
    session[:user_id].present?
  end

  def admin?
    @user = User.find(session[:user_id]) if logged_in?
    @user.privilege.present? if logged_in?
  end

  def user
    @user = User.find(session[:user_id]) if logged_in?
  end

end

app/views/categories/_form.html.erb
<%= error_messages_for(@category) %>

<div class="form-group">

	<%= f.label(:Category) %>
	<%=f.text_field((:name), :class => 'form-control') %>

	<%= f.label(:Description) %>
	<%=f.text_field((:description), :class => 'form-control') %>

	<%= f.label :image, "Image" %>
	<%= f.file_field(:image) %>

	<%= f.label(:visible) %>
	<%= f.check_box(:visible) %>

</div>

app/views/categories/_manage_row.html.erb
<center><%= pluralize(@categories.size, 'category') %>
	found.</center>
<table class="table">
	<tr>
		<th>Image</th>
		<th>Category</th>
		<th>Description</th>
		<th>Action</th>
	</tr>

	<tr><% @categories.each do |category| %>
		<td>
			<%= image_tag category.image.url(:medium) %></td>
		<td><%= category.name%></td>
		<td><%= category.description%></td>
		<td>
			<div class="btn-group">
				<%= link_to("Edit", {:action => 'edit', :id => category.id}, :class => 'btn btn-primary')%>
				<%= link_to "Delete", category, { data: { confirm: "Are you sure you wish to delete the category '#{category.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
				<%unless category.visible.present? %>
				<%= link_to("Accept",{:action => 'accept', :id => category.id}, :class => 'btn btn-primary')%>
				<%end%>
			</div>
		</td>
	</tr>
	<%end%>
</table>

app/views/categories/contact.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well">
      <div class="row">
        <div class="col-md-12">
          <h3>Have you any problem or question ?</h3>
          <p>Contact with us admin@arden.com
          </p>

          <h3>Author</h3>
          <p>Bartosz Betka</p>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/destroy.js.erb
$(".manage-row").html("<%= escape_javascript(render 'categories/manage_row') %>")
$(".notice").html("<%= flash[:notice] %>")

app/views/categories/edit.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<nav aria-label="...">
			<ul class="pager">
				<li class="previous"><%= link_to manage_categories_path do %>
					<span aria-hidden="true" style="color: #B5B5B5;">&larr;Back to category manage</span>
				</li><%end%>
			</ul>
		</nav>
		<div class="well">

			<%=form_for @category do |f| %>
			<%= render(:partial => "form", :locals => {:f => f}) %>

			<div class="row">
				<div class="col-md-6 col-md-offset-6">
					<%= submit_tag(("Update Category"), :class=> "btn btn-primary") %>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/categories/index.html.erb
<div class="row">
  <% @categories.each do |category| %>
  <%= link_to({:controller => 'products', :action => 'index', :category_id => category.id}) do %>
  <div class="col-md-3 col-sm-3 col-xs-12">
    <div class="well">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <%= category.name%>
          <%= image_tag category.image.url(:medium), :class=>'img-responsive' %>
          <%= category.description%>
        </div>
      </div>
    </div>
  </div>

  <% end %>
  <% end %>

</div>

app/views/categories/manage.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="well">
			<%= link_to("Add new category", {:action => 'new'}, :class => 'btn btn-primary') %>

			<div class="manage-row">
				<%= render 'categories/manage_row'%>
			</div>
		</div>
	</div>
</div>

app/views/categories/new.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<nav aria-label="...">
			<ul class="pager">
				<li class="previous"><%= link_to manage_categories_path do %>
					<span aria-hidden="true" style="color: #B5B5B5;">&larr;Back to product manage</span>
				</li><%end%>
			</ul>
		</nav>
		<div class="well">

			<%= form_for(:category, :url => {:action => 'create'}, :html =>{multipart: true}) do |f| %>
			<%= render(:partial => 'form', :locals => {:f => f} ) %>
			<div class="row">
				<div class="col-md-6 col-md-offset-6">
					<%= submit_tag 'Create category', :class => 'btn btn-primary' %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>